# Generated by Django 2.2.6 on 2020-03-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=40)),
                ('receiver', models.CharField(max_length=40)),
                ('subject', models.TextField(max_length=100)),
                ('body', models.TextField(max_length=1000)),
                ('read', models.BooleanField(default=False)),
                ('trashed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(blank=True, default=None)),
            ],
        ),
    ]
