# Generated by Django 3.0.6 on 2020-07-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='simmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=40)),
                ('receiver', models.CharField(max_length=40)),
                ('subject', models.TextField(max_length=100)),
                ('body', models.TextField(max_length=1000)),
                ('read', models.BooleanField(default=False)),
                ('intrashed', models.BooleanField(default=False)),
                ('outtrashed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(blank=True, default=None)),
            ],
        ),
    ]
