# Generated by Django 2.2.6 on 2020-03-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simchat', '0002_auto_20200319_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simmessage',
            old_name='trashed',
            new_name='intrashed',
        ),
        migrations.AddField(
            model_name='simmessage',
            name='outtrashed',
            field=models.BooleanField(default=False),
        ),
    ]
