# Generated by Django 3.0.6 on 2020-07-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='master_user_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=25)),
                ('deletestatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='useraccounts',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=10)),
                ('user_type', models.CharField(max_length=25)),
                ('userpassword', models.CharField(max_length=1000)),
                ('userrole', models.CharField(blank=True, max_length=25)),
                ('registered_at', models.DateTimeField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('loginstatus', models.BooleanField(default=True)),
                ('accountstatus', models.BooleanField(default=True)),
            ],
        ),
    ]
