# Generated by Django 2.2.5 on 2020-03-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='useraccounts',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=10)),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Non-Admin', 'Non-Admin'), ('Dealing-Admin', 'Dealing-Admin')], max_length=15)),
                ('userpassword', models.CharField(max_length=1000)),
                ('userrole', models.CharField(blank=True, max_length=25)),
                ('registered_at', models.DateTimeField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('loginstatus', models.BooleanField(default=True)),
                ('accountstatus', models.BooleanField(default=True)),
            ],
        ),
    ]
