# Generated by Django 2.2.6 on 2020-03-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='useraccounts',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=10)),
                ('user_type', models.CharField(max_length=15)),
                ('userpassword', models.CharField(max_length=1000)),
                ('userrole', models.CharField(max_length=25)),
            ],
        ),
    ]
