# Generated by Django 3.0.6 on 2020-09-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='loginstatus',
            field=models.BooleanField(default=False),
        ),
    ]
