# Generated by Django 2.2.6 on 2020-03-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Non-Admin', 'Non-Admin'), ('Dealing-Admin', 'Dealing-Admin')], max_length=15),
        ),
    ]
