# Generated by Django 2.2.6 on 2020-03-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='registered_at',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
