# Generated by Django 3.0.6 on 2020-06-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_master_user_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='user_type',
            field=models.CharField(max_length=15),
        ),
    ]
