# Generated by Django 2.2.6 on 2020-03-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200301_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='email',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Non-Admin', 'Non-Admin'), ('Dealing-Admin', 'Dealing-Admin')], max_length=15),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='userpassword',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
