# Generated by Django 2.2.6 on 2020-03-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_useraccounts_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='registered_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
