# Generated by Django 2.2.6 on 2020-03-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200317_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='accountstatus',
            field=models.BooleanField(default=False),
        ),
    ]
