# Generated by Django 3.0.6 on 2020-06-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200618_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_user_types',
            name='user_type',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='user_type',
            field=models.CharField(max_length=25),
        ),
    ]
