# Generated by Django 3.0.6 on 2020-06-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200619_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_user_types',
            name='delete',
            field=models.BooleanField(default=True),
        ),
    ]
