# Generated by Django 3.0.6 on 2020-06-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_master_user_types_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master_user_types',
            old_name='delete',
            new_name='deletestatus',
        ),
    ]
