# Generated by Django 2.2.6 on 2020-03-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20200301_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
