# Generated by Django 3.0.6 on 2020-07-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_operationlogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(blank=True, default=None)),
                ('operation', models.CharField(default=None, max_length=100)),
                ('quantity', models.BigIntegerField()),
                ('initial_quantity', models.BigIntegerField()),
                ('final_quantity', models.BigIntegerField()),
                ('issued_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product_transaction_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(blank=True, default=None)),
                ('message', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='sessionlogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(blank=True, default=None)),
                ('message', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
