# Generated by Django 2.2.6 on 2020-03-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlogs',
            name='message',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
