# Generated by Django 3.0.6 on 2020-06-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlogs',
            name='message',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
