# Generated by Django 3.0.6 on 2020-08-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_operationlogs',
            name='issued_by',
            field=models.CharField(max_length=40),
        ),
    ]
