# Generated by Django 2.2.5 on 2020-06-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_product_transaction_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_operationlogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(blank=True, default=None)),
                ('operation', models.CharField(default=None, max_length=100)),
                ('Quantity', models.BigIntegerField()),
                ('initial_quantity', models.BigIntegerField()),
                ('Final_quantity', models.BigIntegerField()),
                ('issued_by', models.CharField(max_length=100)),
            ],
        ),
    ]
