# Generated by Django 2.2.5 on 2020-06-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_product_operationlogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_operationlogs',
            old_name='Final_quantity',
            new_name='final_quantity',
        ),
        migrations.RenameField(
            model_name='product_operationlogs',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
