# Generated by Django 2.2.5 on 2020-03-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productlist',
            fields=[
                ('product_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('product_category', models.CharField(choices=[('stationery', 'stationery'), ('electronics', 'electronics'), ('others', 'others')], default='others', max_length=50)),
                ('product_type', models.CharField(choices=[('consumable', 'consumable'), ('non-consumable', 'non-consumable')], max_length=20)),
                ('available_quantity', models.BigIntegerField()),
                ('arrival_date', models.DateTimeField(blank=True)),
                ('measure_unit', models.CharField(choices=[('kilogaram', 'kilogram'), ('metres', 'metres'), ('inches', 'inches'), ('units', 'units')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
