# Generated by Django 3.0.6 on 2020-06-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='master_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='master_units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='nonconsumable_productlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('issued_to', models.CharField(blank=True, max_length=200)),
                ('issued_by', models.CharField(blank=True, max_length=200)),
                ('units', models.BigIntegerField(blank=True)),
                ('issue_date', models.DateTimeField(blank=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('return_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='productlist',
            fields=[
                ('product_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('product_category', models.CharField(max_length=50)),
                ('product_type', models.CharField(choices=[('consumable', 'consumable'), ('non-consumable', 'non-consumable')], max_length=20)),
                ('available_quantity', models.BigIntegerField()),
                ('arrival_date', models.DateTimeField(blank=True)),
                ('measure_unit', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='productlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('quantity', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(blank=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
