# Generated by Django 2.2.5 on 2020-03-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('quantity', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(blank=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
