# Generated by Django 3.0.6 on 2020-08-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonconsumable_productlog',
            name='issued_by',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='nonconsumable_productlog',
            name='issued_to',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
