# Generated by Django 2.2.5 on 2020-03-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='productlist',
            name='product_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
