# Generated by Django 2.2.5 on 2020-06-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlog',
            name='approved_quantity',
            field=models.BigIntegerField(blank=True, default=None),
        ),
    ]
