# Generated by Django 2.2.5 on 2020-03-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200303_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='product_category',
            field=models.CharField(choices=[('stationery', 'stationery'), ('electronics', 'electronics'), ('others', 'others')], default='others', max_length=50),
        ),
    ]
