# Generated by Django 3.0.6 on 2020-06-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='master_category',
            fields=[
                ('product_category', models.CharField(max_length=50)),
                ('category_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='master_units',
            fields=[
                ('measure_unit', models.CharField(max_length=20)),
                ('unit_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='nonconsumable_productlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('issued_to', models.CharField(blank=True, max_length=200)),
                ('issued_by', models.CharField(blank=True, max_length=200)),
                ('units', models.BigIntegerField(blank=True)),
                ('issue_date', models.DateTimeField(blank=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('return_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='productlist',
            name='measure_unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='product_category',
            field=models.CharField(max_length=50),
        ),
    ]
