# Generated by Django 2.2.5 on 2020-06-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productlog_approved_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconsumable_productlog',
            name='requested_quantity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
