# Generated by Django 2.2.5 on 2020-03-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200303_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='arrival_date',
        ),
    ]
