# Generated by Django 2.2.5 on 2020-07-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_nonconsumable_productlog_requested_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconsumable_productlog',
            name='return_request',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
