# Generated by Django 2.2.5 on 2020-07-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_nonconsumable_productlog_product_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconsumable_productlog',
            name='product_accepted',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
