# Generated by Django 2.2.6 on 2020-03-04 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productlist_arrival_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 4, 15, 26, 11, 965712)),
        ),
    ]
