# Generated by Django 2.2.5 on 2020-07-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_nonconsumable_productlog_product_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlog',
            name='issued_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
