# Generated by Django 2.2.6 on 2020-03-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200304_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='arrival_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
